### ISSUE TITLE
[Enhancement]: put the new arduino UI version into edge channel

### ISSUE THREAD

**Issue by Feichtmeier** [snapcrafters/arduino#30] opened 2022-07-21 12:30 UTC
### What changes would you like?

I would love if you could provide the new arduino UI version inside the edge channel. I need it at work for many users and the snap is the best solution for this :)
Thanks and best regards

**Comment by merlijn-sebrechts** [comment] 2022-12-09 13:55
duplicate of https://github.com/snapcrafters/arduino/issues/32

**Closed as completed by merlijn-sebrechts** 2022-12-09 13:55 UTC
Labels: enhancement
